<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title>Next Framework <?php echo $this -> title; ?></title>

  <style type="text/css">

    html, body {
        height: 100%;
    }

    body {
        margin: 0;
    }

    #wrapper {
        align-items: center;
        display: -webkit-box;
        display: -moz-box;
        display: -ms-flexbox;
        display: -webkit-flex;
        display: flex;
        height: 100%;
        justify-content: center;
    }

    figcaption {
        text-align: center;
    }

        .quote {
            font-size: 3.5vh;
        }

        small {
            font-size: 2.5vh;
        }

  </style>

</head>

<body>

  <div id="wrapper">

    <figure>

        <img src='/logo.png' />

        <figcaption>

            <?php if( isset( $this -> quote ) ) : ?>
            <p class="quote">
                <?php echo $this -> quote; ?>
            </p>
            <?php endif; ?>

            <p>
                <small>
                    <?php echo $this -> footnote; ?>
                </small>
            </p>

        </figcaption>

    </figure>

  </div>

</body>

</html>